# Generated by Django 5.0.2 on 2024-02-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='text',
            field=models.TextField(default='class Solution:\n'),
        ),
    ]
