# Generated by Django 5.0.2 on 2024-02-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_submission_snippet_alter_snippet_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('created_at',)},
        ),
    ]
