# Generated by Django 5.0.2 on 2024-02-18 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_snippet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('-created_at', '-user', '-submission_language', '-status')},
        ),
        migrations.AddField(
            model_name='snippet',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Failed', 'Failed')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='submission_language',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
